# Generated by Django 2.1.7 on 2019-06-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='hone',
            new_name='phone',
        ),
    ]
